# Generated by Django 4.0.10 on 2023-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
