# Generated by Django 4.0.10 on 2023-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_tasks', '0002_rename_title_task_title_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.IntegerField(db_index=True),
        ),
    ]
