# Generated by Django 4.0.10 on 2023-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_users', '0002_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('EM', 'Employee'), ('MO', 'Moderator'), ('MA', 'Manager')], default='EM', max_length=2),
        ),
    ]
